ALTER TABLE `rin_indx`.`faturamento` ADD COLUMN `STATUS_TRANSMITIDA` VARCHAR(1) NULL  AFTER `CFOP` , ADD COLUMN `STATUS_CANCELADO` VARCHAR(1) NULL  AFTER `STATUS_TRANSMITIDA` , ADD COLUMN `STATUS_INUTILIZADO` VARCHAR(1) NULL  AFTER `STATUS_CANCELADO` , ADD COLUMN `STATUS_EMAIL` VARCHAR(1) NULL  AFTER `STATUS_INUTILIZADO` , ADD COLUMN `CHAVE_ACESSO_NFE` VARCHAR(200) NULL  AFTER `STATUS_EMAIL` , ADD COLUMN `PROTOCOLO_NFE` VARCHAR(200) NULL  AFTER `CHAVE_ACESSO_NFE` ;

ALTER TABLE `rin_indx`.`faturamento` ADD COLUMN `STATUS_RETORNO` VARCHAR(50) NULL  AFTER `CHAVE2` ;

ALTER TABLE `rin_indx`.`faturamento` ADD COLUMN `XML` LONGBLOB NULL  AFTER `STATUS_RETORNO` ;

ALTER TABLE `rin_indx`.`faturamento` ADD COLUMN `JUSTIFICATIVA` VARCHAR(50) NULL  AFTER `XML` ;